services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: pgparaboladmin
      POSTGRES_PASSWORD: parabol
      POSTGRES_DB: parabol-saas
    volumes:
      - parabol-old:/var/lib/postgresql/data

  redis:
    image: redis:8.4.0-alpine
    restart: unless-stopped

  parabol:
    image: ghcr.io/RooTender/bibently_hub/parabol:latest
    restart: unless-stopped
    env_file: [.env]
    ports:
      - "10001:10001"
    environment:
      POSTGRES_HOST: postgres
      REDIS_URL: redis://redis:6379
    command: ["node", "./dist/web.js"]
    volumes:
      - parabol-data:/home/node/parabol/self-hosted
